CMSTinyMCEBundle:
    resource: "@CMSTinyMCEBundle/Resources/config/routing.xml"
    prefix:   /

soanata_user:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

blog:
    resource: "@CMSBlogBundle/Resources/config/routing.yml"
   
_imagine:
    resource: .
    type:     imagine
    
cms_admin:
    resource: "@CMSAdminBundle/Resources/config/routing.yml"
    prefix:   /cms_admin
    
_cms_admin:
    resource: .
    prefix:   /cms_admin
    type:     cms_admin
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

homepage:
   pattern:  /
   defaults: { _controller: CMSMainBundle:Default:index }
